### ISSUE TITLE
java.lang.NullPointerException (no error message)

### ISSUE THREAD

**Issue by Epic-Apps-Hub** [lschmierer/android_play_install_referrer#20]
hi, i am using all versions like the example project but i get these errors
here is my run with verbose 
```
[  +50 ms] executing: [C:\Users\mahmoud\Documents\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +48 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 18116933e77adc82f80866c928266a5b4f1ed645
[        ] executing: [C:\Users\mahmoud\Documents\flutter/] git tag --points-at 18116933e77adc82f80866c928266a5b4f1ed645
[  +37 ms] Exit code 0 from: git tag --points-at 18116933e77adc82f80866c928266a5b4f1ed645
[        ] 2.5.3
[   +6 ms] executing: [C:\Users\mahmoud\Documents\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +26 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\Users\mahmoud\Documents\flutter/] git ls-remote --get-url origin
[  +26 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +82 ms] executing: [C:\Users\mahmoud\Documents\flutter/] git rev-parse --abbrev-ref HEAD
[  +27 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +60 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +46 ms] executing: C:\Users\mahmoud\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +32 ms] List of devices attached
           c58cf70f               device product:beryllium model:POCO_F1 device:beryllium transport_id:3
[   +4 ms] C:\Users\mahmoud\AppData\Local\Android\sdk\platform-tools\adb.exe -s c58cf70f shell getprop
[  +85 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +5 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +38 ms] Changing current working directory to: G:\files from old windows\latest wool\wool
[  +53 ms] Skipping pub get: version match.
[  +16 ms] Found plugin android_play_install_referrer at
C:\Users\mahmoud\Documents\flutter\.pub-cache\hosted\pub.dartlang.org\android_play_install_referrer-0.2.1\
[   +8 ms] Found plugin appmetrica_sdk at C:\Users\mahmoud\Documents\flutter\.pub-cache\hosted\pub.dartlang.org\appmetrica_sdk-0.0.7+1\
[  +16 ms] Found plugin device_info at C:\Users\mahmoud\Documents\flutter\.pub-cache\hosted\pub.dartlang.org\device_info-2.0.3\
[   +4 ms] Found plugin disable_battery_optimization at C:\Users\mahmoud\Documents\flutter\.pub-cache\hosted\pub.dartlang.org\disable_battery_optimization-0.1.2\
[   +5 ms] Found plugin firebase_auth at C:\Users\mahmoud\Documents\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-3.1.1\
[   +3 ms] Found plugin firebase_auth_web at C:\Users\mahmoud\Documents\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth_web-3.1.0\
[   +1 ms] Found plugin firebase_core at C:\Users\mahmoud\Documents\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-1.12.0\
[   +1 ms] Found plugin firebase_core_web at C:\Users\mahmoud\Documents\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core_web-1.5.4\
[   +1 ms] Found plugin firebase_messaging at C:\Users\mahmoud\Documents\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_messaging-10.0.7\
[   +1 ms] Found plugin firebase_messaging_web at C:\Users\mahmoud\Documents\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_messaging_web-2.0.5\
[   +1 ms] Found plugin flutter_admob_app_open at C:\Users\mahmoud\Documents\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_admob_app_open-1.1.1\
[   +3 ms] Found plugin flutter_email_sender at C:\Users\mahmoud\Documents\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_email_sender-5.0.2\
[   +1 ms] Found plugin flutter_isolate at C:\Users\mahmoud\Documents\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_isolate-2.0.0\
[   +1 ms] Found plugin flutter_local_notifications at C:\Users\mahmoud\Documents\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_local_notifications-8.2.0\
[   +6 ms] Found plugin fluttertoast at C:\Users\mahmoud\Documents\flutter\.pub-cache\hosted\pub.dartlang.org\fluttertoast-8.0.8\
[   +1 ms] Found plugin google_mobile_ads at C:\Users\mahmoud\Documents\flutter\.pub-cache\hosted\pub.dartlang.org\google_mobile_ads-0.13.6\
[   +1 ms] Found plugin google_sign_in at C:\Users\mahmoud\Documents\flutter\.pub-cache\hosted\pub.dartlang.org\google_sign_in-5.1.0\
[   +1 ms] Found plugin google_sign_in_web at C:\Users\mahmoud\Documents\flutter\.pub-cache\hosted\pub.dartlang.org\google_sign_in_web-0.10.0+3\
[   +3 ms] Found plugin image_gallery_saver at C:\Users\mahmoud\Documents\flutter\.pub-cache\hosted\pub.dartlang.org\image_gallery_saver-1.6.9\
[   +1 ms] Found plugin in_app_review at C:\Users\mahmoud\Documents\flutter\.pub-cache\hosted\pub.dartlang.org\in_app_review-2.0.3\
[   +5 ms] Found plugin native_admob_flutter at C:\Users\mahmoud\Documents\flutter\.pub-cache\hosted\pub.dartlang.org\native_admob_flutter-1.5.0\
[   +3 ms] Found plugin path_provider at C:\Users\mahmoud\Documents\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-2.0.5\
[        ] Found plugin path_provider_linux at C:\Users\mahmoud\Documents\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_linux-2.1.0\
[   +1 ms] Found plugin path_provider_macos at C:\Users\mahmoud\Documents\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_macos-2.0.2\
[   +1 ms] Found plugin path_provider_windows at C:\Users\mahmoud\Documents\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_windows-2.0.3\
[   +2 ms] Found plugin permission_handler at C:\Users\mahmoud\Documents\flutter\.pub-cache\hosted\pub.dartlang.org\permission_handler-8.1.6\
[   +5 ms] Found plugin screen_brightness at C:\Users\mahmoud\Documents\flutter\.pub-cache\hosted\pub.dartlang.org\screen_brightness-0.0.4\
[        ] Found plugin share at C:\Users\mahmoud\Documents\flutter\.pub-cache\hosted\pub.dartlang.org\share-2.0.4\
[   +4 ms] Found plugin sqflite at C:\Users\mahmoud\Documents\flutter\.pub-cache\hosted\pub.dartlang.org\sqflite-2.0.0+4\
[   +9 ms] Found plugin uni_links at C:\Users\mahmoud\Documents\flutter\.pub-cache\hosted\pub.dartlang.org\uni_links-0.5.1\
[   +1 ms] Found plugin uni_links_web at C:\Users\mahmoud\Documents\flutter\.pub-cache\hosted\pub.dartlang.org\uni_links_web-0.1.0\
[   +1 ms] Found plugin url_launcher at C:\Users\mahmoud\Documents\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher-6.0.17\
[   +1 ms] Found plugin url_launcher_android at C:\Users\mahmoud\Documents\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_android-6.0.13\
[        ] Found plugin url_launcher_ios at C:\Users\mahmoud\Documents\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_ios-6.0.13\
[        ] Found plugin url_launcher_linux at C:\Users\mahmoud\Documents\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_linux-2.0.2\
[        ] Found plugin url_launcher_macos at C:\Users\mahmoud\Documents\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_macos-2.0.2\
[   +1 ms] Found plugin url_launcher_web at C:\Users\mahmoud\Documents\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_web-2.0.4\
[        ] Found plugin url_launcher_windows at C:\Users\mahmoud\Documents\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_windows-2.0.2\
[   +2 ms] Found plugin wallpaper_manager at C:\Users\mahmoud\Documents\flutter\.pub-cache\hosted\pub.dartlang.org\wallpaper_manager-1.0.10\
[   +2 ms] Found plugin workmanager at C:\Users\mahmoud\Documents\flutter\.pub-cache\hosted\pub.dartlang.org\workmanager-0.4.1\
[ +100 ms] Found plugin android_play_install_referrer at
C:\Users\mahmoud\Documents\flutter\.pub-cache\hosted\pub.dartlang.org\android_play_install_referrer-0.2.1\
[   +2 ms] Found plugin appmetrica_sdk at C:\Users\mahmoud\Documents\flutter\.pub-cache\hosted\pub.dartlang.org\appmetrica_sdk-0.0.7+1\
[   +7 ms] Found plugin device_info at C:\Users\mahmoud\Documents\flutter\.pub-cache\hosted\pub.dartlang.org\device_info-2.0.3\
[   +1 ms] Found plugin disable_battery_optimization at C:\Users\mahmoud\Documents\flutter\.pub-cache\hosted\pub.dartlang.org\disable_battery_optimization-0.1.2\
[   +3 ms] Found plugin firebase_auth at C:\Users\mahmoud\Documents\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-3.1.1\
[   +1 ms] Found plugin firebase_auth_web at C:\Users\mahmoud\Documents\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth_web-3.1.0\
[   +1 ms] Found plugin firebase_core at C:\Users\mahmoud\Documents\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-1.12.0\
[   +1 ms] Found plugin firebase_core_web at C:\Users\mahmoud\Documents\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core_web-1.5.4\
[        ] Found plugin firebase_messaging at C:\Users\mahmoud\Documents\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_messaging-10.0.7\
[   +1 ms] Found plugin firebase_messaging_web at C:\Users\mahmoud\Documents\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_messaging_web-2.0.5\
[        ] Found plugin flutter_admob_app_open at C:\Users\mahmoud\Documents\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_admob_app_open-1.1.1\
[   +2 ms] Found plugin flutter_email_sender at C:\Users\mahmoud\Documents\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_email_sender-5.0.2\
[        ] Found plugin flutter_isolate at C:\Users\mahmoud\Documents\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_isolate-2.0.0\
[        ] Found plugin flutter_local_notifications at C:\Users\mahmoud\Documents\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_local_notifications-8.2.0\  
[   +3 ms] Found plugin fluttertoast at C:\Users\mahmoud\Documents\flutter\.pub-cache\hosted\pub.dartlang.org\fluttertoast-8.0.8\
[   +1 ms] Found plugin google_mobile_ads at C:\Users\mahmoud\Documents\flutter\.pub-cache\hosted\pub.dartlang.org\google_mobile_ads-0.13.6\
[        ] Found plugin google_sign_in at C:\Users\mahmoud\Documents\flutter\.pub-cache\hosted\pub.dartlang.org\google_sign_in-5.1.0\
[   +1 ms] Found plugin google_sign_in_web at C:\Users\mahmoud\Documents\flutter\.pub-cache\hosted\pub.dartlang.org\google_sign_in_web-0.10.0+3\
[   +2 ms] Found plugin image_gallery_saver at C:\Users\mahmoud\Documents\flutter\.pub-cache\hosted\pub.dartlang.org\image_gallery_saver-1.6.9\
[        ] Found plugin in_app_review at C:\Users\mahmoud\Documents\flutter\.pub-cache\hosted\pub.dartlang.org\in_app_review-2.0.3\
[   +3 ms] Found plugin native_admob_flutter at C:\Users\mahmoud\Documents\flutter\.pub-cache\hosted\pub.dartlang.org\native_admob_flutter-1.5.0\
[   +3 ms] Found plugin path_provider at C:\Users\mahmoud\Documents\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-2.0.5\
[        ] Found plugin path_provider_linux at C:\Users\mahmoud\Documents\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_linux-2.1.0\
[   +1 ms] Found plugin path_provider_macos at C:\Users\mahmoud\Documents\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_macos-2.0.2\
[   +1 ms] Found plugin path_provider_windows at C:\Users\mahmoud\Documents\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_windows-2.0.3\
[   +1 ms] Found plugin permission_handler at C:\Users\mahmoud\Documents\flutter\.pub-cache\hosted\pub.dartlang.org\permission_handler-8.1.6\
[   +4 ms] Found plugin screen_brightness at C:\Users\mahmoud\Documents\flutter\.pub-cache\hosted\pub.dartlang.org\screen_brightness-0.0.4\
[        ] Found plugin share at C:\Users\mahmoud\Documents\flutter\.pub-cache\hosted\pub.dartlang.org\share-2.0.4\
[   +1 ms] Found plugin sqflite at C:\Users\mahmoud\Documents\flutter\.pub-cache\hosted\pub.dartlang.org\sqflite-2.0.0+4\
[   +3 ms] Found plugin uni_links at C:\Users\mahmoud\Documents\flutter\.pub-cache\hosted\pub.dartlang.org\uni_links-0.5.1\
[        ] Found plugin uni_links_web at C:\Users\mahmoud\Documents\flutter\.pub-cache\hosted\pub.dartlang.org\uni_links_web-0.1.0\
[        ] Found plugin url_launcher at C:\Users\mahmoud\Documents\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher-6.0.17\
[        ] Found plugin url_launcher_android at C:\Users\mahmoud\Documents\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_android-6.0.13\
[        ] Found plugin url_launcher_ios at C:\Users\mahmoud\Documents\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_ios-6.0.13\
[   +1 ms] Found plugin url_launcher_linux at C:\Users\mahmoud\Documents\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_linux-2.0.2\
[   +1 ms] executing: C:\Users\mahmoud\AppData\Local\Android\sdk\platform-tools\adb.exe start-server
[  +17 ms] Building APK
[  +16 ms] Running Gradle task 'assembleDebug'...
[   +3 ms] Using gradle from G:\files from old windows\latest wool\wool\android\gradlew.bat.
[  +10 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
[  +95 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
[        ] openjdk version "11.0.10" 2021-01-19
           OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
           OpenJDK 64-Bit Server VM (build 11.0.10+0-b96-7249189, mixed mode)
[   +1 ms] executing: [G:\files from old windows\latest wool\wool\android/] G:\files from old windows\latest wool\wool\android\gradlew.bat -Pverbose=true        
-Ptarget-platform=android-arm64 -Ptarget=G:\files from old windows\latest wool\wool\lib\main.dart -Pdart-defines=RkxVVFRFUl9XRUJfQVVUT19ERVRFQ1Q9dHJ1ZQ==        
-Pdart-obfuscation=false -Pextra-front-end-options=--no-sound-null-safety -Ptrack-widget-creation=true -Ptree-shake-icons=false
-Pfilesystem-scheme=org-dartlang-root assembleDebug
[ +857 ms] > Configure project :app
[        ] WARNING: The option setting 'android.enableR8=true' is deprecated.
[        ] It will be removed in version 5.0 of the Android Gradle plugin.
[        ] You will no longer be able to disable R8
[+1294 ms] > Task :android_play_install_referrer:preBuild UP-TO-DATE
[        ] > Task :android_play_install_referrer:preDebugBuild UP-TO-DATE
[        ] > Task :android_play_install_referrer:compileDebugAidl NO-SOURCE
[        ] > Task :android_play_install_referrer:mergeDebugJniLibFolders UP-TO-DATE
[        ] > Task :android_play_install_referrer:mergeDebugNativeLibs NO-SOURCE
[        ] > Task :android_play_install_referrer:stripDebugDebugSymbols NO-SOURCE
[        ] > Task :android_play_install_referrer:copyDebugJniLibsProjectAndLocalJars UP-TO-DATE
[        ] > Task :android_play_install_referrer:compileDebugRenderscript NO-SOURCE
[        ] > Task :android_play_install_referrer:generateDebugBuildConfig UP-TO-DATE
[        ] > Task :android_play_install_referrer:generateDebugResValues UP-TO-DATE
[        ] > Task :android_play_install_referrer:generateDebugResources UP-TO-DATE
[        ] > Task :android_play_install_referrer:packageDebugResources UP-TO-DATE
[        ] > Task :android_play_install_referrer:parseDebugLocalResources UP-TO-DATE
[  +96 ms] > Task :android_play_install_referrer:processDebugManifest UP-TO-DATE
[ +300 ms] > Task :android_play_install_referrer:javaPreCompileDebug UP-TO-DATE
[        ] > Task :android_play_install_referrer:mergeDebugShaders UP-TO-DATE
[        ] > Task :android_play_install_referrer:compileDebugShaders NO-SOURCE
[        ] > Task :android_play_install_referrer:generateDebugAssets UP-TO-DATE
[        ] > Task :android_play_install_referrer:packageDebugAssets UP-TO-DATE
[        ] > Task :android_play_install_referrer:packageDebugRenderscript NO-SOURCE
[        ] > Task :android_play_install_referrer:prepareLintJarForPublish UP-TO-DATE
[        ] > Task :android_play_install_referrer:processDebugJavaRes NO-SOURCE
[        ] > Task :android_play_install_referrer:writeDebugAarMetadata UP-TO-DATE
[        ] > Task :android_play_install_referrer:generateDebugRFile
[        ] > Task :app:compileFlutterBuildDebug FAILED
[        ] Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
[        ] Use '--warning-mode all' to show the individual deprecation warnings.
[        ] See https://docs.gradle.org/6.5/userguide/command_line_interface.html#sec:command_line_warnings
[        ] 14 actionable tasks: 2 executed, 12 up-to-date
[        ] FAILURE: Build failed with an exception.
[        ] * What went wrong:
[        ] Execution failed for task ':app:compileFlutterBuildDebug'.
[        ] > java.lang.NullPointerException (no error message)
[        ] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[   +1 ms] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 2s
[ +391 ms] Running Gradle task 'assembleDebug'... (completed in 3.1s)
[+7550 ms] Exception: Gradle task assembleDebug failed with exit code 1
[   +1 ms] "flutter run" took 11,517ms.
[   +3 ms]
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:669:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1125:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:92:3)
           <asynchronous suspension>


[  +66 ms] ensureAnalyticsSent: 64ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1
```

my pubspec  
```
name: wool
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+2

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  animated_theme_switcher: ^2.0.1
  animations: ^2.0.1
  another_flushbar: ^1.10.24
  blur: null
  cached_network_image: ^3.1.0
  cupertino_icons: ^1.0.2
  dio: ^4.0.0
  dio_http_cache: ^0.3.0
  easy_container: null
  feedback: null
  firebase_auth: ^3.1.1
  firebase_core: ^1.6.0
  firebase_messaging: ^10.0.7
  flutter:
    sdk: flutter
 # flutter_admob_app_open: ^1.1.1
  flutter_bloc: ^7.2.0
  flutter_bounce: ^1.1.0
  flutter_cache_manager: null
  flutter_email_sender: ^5.0.2
#  flutter_inbrain: null
  flutter_isolate: ^2.0.0
  flutter_local_notifications: ^8.2.0
#  flutter_pollfish: ^4.0.1
 # flutter_restart: ^0.0.3
  flutter_screenutil: null
  flutter_spinkit: ^5.0.0
 # flutterappziloofferwall: ^0.0.1
  fluttericon: ^2.0.0
  fluttertoast: ^8.0.8
 # google_mobile_ads: ^0.13.5
  google_sign_in: ^5.1.0
  hive: ^2.0.4
  image_gallery_saver: ^1.6.9
  in_app_review: ^2.0.3
 # native_admob_flutter: ^1.5.0
  octo_image: null
  path_provider: ^2.0.5
  permission_handler: ^8.1.4+2
  pull_to_refresh: ^2.0.0
  screen_brightness: null
  share: ^2.0.4
  slide_digital_clock: ^1.0.2
  switcher_button: ^0.0.4
  uni_links: ^0.5.1
  wallpaper_manager: ^1.0.9
 # webview_flutter: ^2.1.2
 # back_button_interceptor: ^5.0.2
  superellipse_shape: null
 # flutter_applovin_max: ^2.0.0
 # unity_ads_plugin: ^0.2.4
 # flutter_ironsource_x:
  #mopub_flutter: ^1.3.0
 # timer_count_down: ^2.2.0
 # startapp: ^0.5.1
##  adcolony_flutter: ^1.4.3
 # appodeal_ads: ^0.6.3
  workmanager: ^0.4.1
 # android_autostart: ^0.0.2
  disable_battery_optimization: ^0.1.2
  flutter_admob_app_open: ^1.1.1
  native_admob_flutter: ^1.5.0
  url_launcher: ^6.0.17
  google_mobile_ads: ^0.13.5
  #flutter_staggered_grid_view: ^0.4.1
 # tiktoklikescroller: ^0.1.8
#  snapping_page_scroll: ^2.0.2
  numberpicker: ^2.1.1
  flutter_rating_bar: ^4.0.0
  appmetrica_sdk: ^0.0.7+1
  uuid: ^3.0.5
  internet_connection_checker: ^0.0.1+3
  lottie: ^1.2.1
  android_play_install_referrer: 0.2.1 
  device_info: ^2.0.3


#  wallpaper_manager_flutter: null
dev_dependencies:
  flutter_launcher_icons: '^0.9.2'
  flutter_native_splash: ^1.2.1
  flutter_test:
    sdk: flutter

flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/icon.png'
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Aeonik
      fonts:
        - asset: assets/Aeonik-Regular.otf
        - asset: assets/Aeonik-Bold.otf
          weight: 700
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
```

flutter doctor 
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.5.3, on Microsoft Windows [Version 10.0.22000.434], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[√] Chrome - develop for the web
[√] Android Studio (version 2020.3)
[√] VS Code (version 1.64.1)
[√] Connected device (3 available)

• No issues found!
```
versions are :
```
----------ext.kotlin_version = '1.3.50'
----------classpath 'com.android.tools.build:gradle:4.1.1'
----------distributionUrl=https\://services.gradle.org/distributions/gradle-6.5-bin.zip
```
please help
